"""Calendar context and a conservative fallback for the Crazy Thursday push.

The normal path is generated by the Node chat client.  This module deliberately
only contains a deterministic fallback so a temporary model outage does not
silently lose a scheduled message.
"""
from __future__ import annotations

from datetime import date, timedelta
import random

# The statutory dates are kept as a small local table on purpose. A scheduled
# group message must not depend on a calendar API being available at send time.
# The table covers the holiday years currently used by this deployment; fixed
# festivals below still provide useful context outside these years.
_MOVABLE_HOLIDAYS = {
    2025: {date(2025, 1, 29): "春节", date(2025, 10, 6): "中秋节"},
    2026: {date(2026, 2, 17): "春节", date(2026, 9, 25): "中秋节"},
    2027: {date(2027, 2, 6): "春节", date(2027, 9, 15): "中秋节"},
    2028: {date(2028, 1, 26): "春节", date(2028, 10, 3): "中秋节"},
}

# Only use adjustment wording when the date is a known working-day swap. This
# avoids inventing an "调休" on an ordinary Thursday.
_ADJUSTMENT_DAYS = {
    date(2025, 9, 28): "国庆前调休上班",
    date(2025, 10, 11): "国庆后调休上班",
    date(2026, 9, 27): "国庆前调休上班",
    date(2026, 10, 10): "国庆后调休上班",
}

_FIXED_HOLIDAYS = (
    ((1, 1), "元旦"),
    ((2, 14), "情人节"),
    ((3, 8), "妇女节"),
    ((4, 4), "清明节"),
    ((5, 1), "劳动节"),
    ((6, 1), "儿童节"),
    ((9, 10), "教师节"),
    ((10, 1), "国庆节"),
    ((11, 11), "双十一"),
    ((12, 25), "圣诞节"),
)


def _holiday_dates(year: int) -> dict[date, str]:
    result = {date(year, month, day): name for (month, day), name in _FIXED_HOLIDAYS}
    result.update(_MOVABLE_HOLIDAYS.get(year, {}))
    return result


def nearby_holiday_context(day: date, window_days: int = 10) -> str:
    """Return a short, user-facing holiday/adjustment hint near ``day``."""
    adjustment = _ADJUSTMENT_DAYS.get(day)
    if adjustment:
        return adjustment
    candidates: list[tuple[int, str]] = []
    for year in (day.year - 1, day.year, day.year + 1):
        for holiday, name in _holiday_dates(year).items():
            delta = (holiday - day).days
            if abs(delta) <= window_days:
                candidates.append((delta, name))
    if not candidates:
        return ""
    delta, name = min(candidates, key=lambda item: (abs(item[0]), item[0]))
    if delta == 0:
        return f"今天是{name}"
    if delta > 0:
        return f"{name}还有{delta}天"
    return f"{name}刚过{abs(delta)}天"


def _adjustment_hint(day: date) -> str:
    if day in _ADJUSTMENT_DAYS:
        return _ADJUSTMENT_DAYS[day]
    nearby = []
    for offset in range(-10, 11):
        candidate = day + timedelta(days=offset)
        if candidate in _ADJUSTMENT_DAYS:
            nearby.append((abs(offset), _ADJUSTMENT_DAYS[candidate]))
    return min(nearby, default=(999, ""))[1]


def generate_crazy_thursday_copy(day: date, *, seed: str = "") -> str:
    """Generate a varied local fallback without an LLM call."""
    holiday = nearby_holiday_context(day)
    rng = random.Random(f"{day.isoformat()}:{seed}")
    context = holiday if holiday and rng.random() < 0.35 else ""
    context_line = f"，顺手提醒一句：{context}" if context else ""
    templates = (
        "疯狂星期四，现通知如下：今天的快乐已经被我临时接管，下午三点统一发放。逾期不候，原因是我也不知道。",
        "今天星期四，宇宙给大家发了好运，我负责签收。想提前领取的先排队，队尾那位不要假装没看见。",
        "疯狂星期四，经过严谨而不存在的会议，我决定把今天的摸鱼批准为战略休息。谁反对，谁负责写会议纪要。",
        "本周四特别活动：把一件小事说得像国策，再把国策忘在下一条消息里。参与方式很简单，保持清醒即可。",
        "疯狂星期四，今天的风有点像加班通知，但我选择把它理解成命运在催大家下班。这个解释暂时有效。",
        "经有关部门研究，今天适合吃点好的、少想点复杂的。至于有关部门是谁，正在忙着给自己盖章。",
        "星期四了，离周末只差一点点认真工作。建议大家不要认真，免得周末发现事情真的做完了。",
        "疯狂星期四，现开放一次性好运兑换窗口。窗口工作人员没有窗口，兑换规则也还在路上。",
    )
    text = rng.choice(templates)
    if context_line:
        text = f"{text}{context_line}"
    if rng.random() < 0.2:
        text += " v 我 50，给这条通知一点行政经费。"
    return text
