"""Calendar context and a conservative fallback for the Crazy Thursday push.

The normal path is generated by the Node chat client.  This module deliberately
only contains a deterministic fallback so a temporary model outage does not
silently lose a scheduled message.
"""
from __future__ import annotations

from datetime import date, timedelta
import random

# The statutory dates are kept as a small local table on purpose. A scheduled
# group message must not depend on a calendar API being available at send time.
# The table covers the holiday years currently used by this deployment; fixed
# festivals below still provide useful context outside these years.
_MOVABLE_HOLIDAYS = {
    2025: {date(2025, 1, 29): "春节", date(2025, 10, 6): "中秋节"},
    2026: {date(2026, 2, 17): "春节", date(2026, 9, 25): "中秋节"},
    2027: {date(2027, 2, 6): "春节", date(2027, 9, 15): "中秋节"},
    2028: {date(2028, 1, 26): "春节", date(2028, 10, 3): "中秋节"},
}

# Only use adjustment wording when the date is a known working-day swap. This
# avoids inventing an "调休" on an ordinary Thursday.
_ADJUSTMENT_DAYS = {
    date(2025, 9, 28): "国庆前调休上班",
    date(2025, 10, 11): "国庆后调休上班",
    date(2026, 9, 27): "国庆前调休上班",
    date(2026, 10, 10): "国庆后调休上班",
}

_FIXED_HOLIDAYS = (
    ((1, 1), "元旦"),
    ((2, 14), "情人节"),
    ((3, 8), "妇女节"),
    ((4, 4), "清明节"),
    ((5, 1), "劳动节"),
    ((6, 1), "儿童节"),
    ((9, 10), "教师节"),
    ((10, 1), "国庆节"),
    ((11, 11), "双十一"),
    ((12, 25), "圣诞节"),
)


def _holiday_dates(year: int) -> dict[date, str]:
    result = {date(year, month, day): name for (month, day), name in _FIXED_HOLIDAYS}
    result.update(_MOVABLE_HOLIDAYS.get(year, {}))
    return result


def nearby_holiday_context(day: date, window_days: int = 10) -> str:
    """Return a short, user-facing holiday/adjustment hint near ``day``."""
    adjustment = _ADJUSTMENT_DAYS.get(day)
    if adjustment:
        return adjustment
    candidates: list[tuple[int, str]] = []
    for year in (day.year - 1, day.year, day.year + 1):
        for holiday, name in _holiday_dates(year).items():
            delta = (holiday - day).days
            if abs(delta) <= window_days:
                candidates.append((delta, name))
    if not candidates:
        return ""
    delta, name = min(candidates, key=lambda item: (abs(item[0]), item[0]))
    if delta == 0:
        return f"今天是{name}"
    if delta > 0:
        return f"{name}还有{delta}天"
    return f"{name}刚过{abs(delta)}天"


def _adjustment_hint(day: date) -> str:
    if day in _ADJUSTMENT_DAYS:
        return _ADJUSTMENT_DAYS[day]
    nearby = []
    for offset in range(-10, 11):
        candidate = day + timedelta(days=offset)
        if candidate in _ADJUSTMENT_DAYS:
            nearby.append((abs(offset), _ADJUSTMENT_DAYS[candidate]))
    return min(nearby, default=(999, ""))[1]


def generate_crazy_thursday_copy(day: date, *, seed: str = "") -> str:
    """Generate a varied local fallback without an LLM call."""
    holiday = nearby_holiday_context(day)
    rng = random.Random(f"{day.isoformat()}:{seed}")
    context = holiday if holiday and rng.random() < 0.35 else ""
    # 节日背景只作为选材信号，不能在成品末尾再补一条无关提醒；那种
    # “故事讲完后顺手加一句”的结构正是疯狂星期四文案要避免的。
    context_line = ""
    # 兜底只保存公开文案库原文和用户给出的处方示例，不再临时编写新句子。
    templates = (
        "抑郁了，医生给我开了一张处方：炸鸡、薯条汉堡、可乐 500ml；今天疯狂星期四，v 我 50。",
        "郑重声明：\n很抱歉打扰大家，本人于今天上午查出饿了，情况紧急\n所幸有个朋友的姥爷是中医，\n让我照着这个药方抓药:  \n鸡肉卷 * 1\n烤翅 * 3 对 \n上校鸡块 * 2\n薯条 * 2   \n可乐 * 700ml\n脆皮鸡 * 2 \n谁 v 我 50 去抓药",
        "今天学了一个新成语叫做闻鸡起舞，意思是闻到肯德基的味道，起码找别人要五十",
        "通知：今天群里禁止发送肯德基文案，有一个算一个，发一次罚 50，罚款交到我这里",
        "人一但有了爱情，智商情商都会提高95% ，烦恼也会消失95%。但问题来了 爱情从哪里来？科学家却不肯说，只留下了一串奇怪的符号：KFC Crazy Thursday",
        "给年轻人的八条建议：1.谈恋爱首先要找你爱的，如果结婚就要找爱你的 2.千万别输在“等”这个字身上 3.永远留住30%的神秘 4.不要低估任何一个人 5.别把没教养当做有气场 6.谈恋爱可以穷，结婚不可以 7.谈恋爱一定要自由 8.v50请我吃肯德基疯狂星期四",
        "早上辛苦写了一早上代码，突然报错，找不到原因。java.lang.NoMoneyException: KFC_CRAZY_THURSDAY_VME50",
        "家人们求助，求姻缘应该去哪个寺庙啊？\nA、灵隐寺\nB、弘法寺\nC、甘露寺\nD、肯德基疯狂星期寺",
        "我有个朋友每个月都会进行几次神秘仪式，和一帮信徒去红色庙里吃禽类碎尸块，还会放上红色和白色的粘稠物质。今天就是他们仪式的日子，v 我 50，我去现场直播给你们看。",
        "寒风吹起，细雨飘落，才察觉严寒的冬天已悄悄而至，这一刻兴许什么都会忘却，唯独不能忘的是向远在他乡的你轻轻说声：“今天肯德基疯狂星期四，V 我 50。”",
        "老师问三个学生，你们用什么东西可以填满一整个房间。第一个学生找来稻草铺满地板，老师摇了摇头。第二个学生找来一根蜡烛点燃，屋子里充满了光，老师还是摇了摇头，因为学生的影子没有被照到。这时第三个学生拿出肯德基疯狂星期四的黄金小酥肉，顿时香味充满了整个房间",
        "真正被爱的人都是直接提需求。没有自信的人，才会在长篇大论里藏一句 v 我 50。你害怕被拒绝的尴尬，把需求都讲成了玩笑话。 所以快 v 我 50",
    )
    # Node 暂时不可用时也不能在夏天回退到“冬天已悄悄而至”。
    eligible = tuple(text for text in templates if "冬天" not in text or day.month in (12, 1, 2))
    text = rng.choice(eligible)
    if context_line:
        text = f"{text}{context_line}"
    return text
