"""Calendar context and a conservative fallback for the Crazy Thursday push.

The normal path is generated by the Node chat client.  This module deliberately
only contains a deterministic fallback so a temporary model outage does not
silently lose a scheduled message.
"""
from __future__ import annotations

from datetime import date, timedelta
import random

# The statutory dates are kept as a small local table on purpose. A scheduled
# group message must not depend on a calendar API being available at send time.
# The table covers the holiday years currently used by this deployment; fixed
# festivals below still provide useful context outside these years.
_MOVABLE_HOLIDAYS = {
    2025: {date(2025, 1, 29): "春节", date(2025, 10, 6): "中秋节"},
    2026: {date(2026, 2, 17): "春节", date(2026, 9, 25): "中秋节"},
    2027: {date(2027, 2, 6): "春节", date(2027, 9, 15): "中秋节"},
    2028: {date(2028, 1, 26): "春节", date(2028, 10, 3): "中秋节"},
}

# Only use adjustment wording when the date is a known working-day swap. This
# avoids inventing an "调休" on an ordinary Thursday.
_ADJUSTMENT_DAYS = {
    date(2025, 9, 28): "国庆前调休上班",
    date(2025, 10, 11): "国庆后调休上班",
    date(2026, 9, 27): "国庆前调休上班",
    date(2026, 10, 10): "国庆后调休上班",
}

_FIXED_HOLIDAYS = (
    ((1, 1), "元旦"),
    ((2, 14), "情人节"),
    ((3, 8), "妇女节"),
    ((4, 4), "清明节"),
    ((5, 1), "劳动节"),
    ((6, 1), "儿童节"),
    ((9, 10), "教师节"),
    ((10, 1), "国庆节"),
    ((11, 11), "双十一"),
    ((12, 25), "圣诞节"),
)


def _holiday_dates(year: int) -> dict[date, str]:
    result = {date(year, month, day): name for (month, day), name in _FIXED_HOLIDAYS}
    result.update(_MOVABLE_HOLIDAYS.get(year, {}))
    return result


def nearby_holiday_context(day: date, window_days: int = 10) -> str:
    """Return a short, user-facing holiday/adjustment hint near ``day``."""
    adjustment = _ADJUSTMENT_DAYS.get(day)
    if adjustment:
        return adjustment
    candidates: list[tuple[int, str]] = []
    for year in (day.year - 1, day.year, day.year + 1):
        for holiday, name in _holiday_dates(year).items():
            delta = (holiday - day).days
            if abs(delta) <= window_days:
                candidates.append((delta, name))
    if not candidates:
        return ""
    delta, name = min(candidates, key=lambda item: (abs(item[0]), item[0]))
    if delta == 0:
        return f"今天是{name}"
    if delta > 0:
        return f"{name}还有{delta}天"
    return f"{name}刚过{abs(delta)}天"


def _adjustment_hint(day: date) -> str:
    if day in _ADJUSTMENT_DAYS:
        return _ADJUSTMENT_DAYS[day]
    nearby = []
    for offset in range(-10, 11):
        candidate = day + timedelta(days=offset)
        if candidate in _ADJUSTMENT_DAYS:
            nearby.append((abs(offset), _ADJUSTMENT_DAYS[candidate]))
    return min(nearby, default=(999, ""))[1]


def generate_crazy_thursday_copy(day: date, *, seed: str = "") -> str:
    """Generate a varied local fallback without an LLM call."""
    holiday = nearby_holiday_context(day)
    rng = random.Random(f"{day.isoformat()}:{seed}")
    context = holiday if holiday and rng.random() < 0.35 else ""
    context_line = f"，顺手提醒一句：{context}" if context else ""
    templates = (
        "研究显示，人在连续工作五天后会把‘下班’误认为一种短暂幻觉。临床观察还发现，听见脆皮两个字时，患者会自动打开外卖软件。论文结论很稳，唯一缺的是样本费。",
        "物业通知：三号楼电梯本周进入节能模式，按一次只上半层，按两次会播放住户童年黑历史。经测试，最快的下楼方式仍是去买东西——我负责路线，预算差一笔。",
        "项目复盘显示，会议减少一小时，生产力上升三个百分点；PPT 少写一页，幸福感上升七个百分点；继续算下去，结论已经通过，付款还差最后一项。",
        "医生问我最近有没有失眠、心慌、对着收银台发呆。我说都有，他点头说是典型的周四综合征，处方写得很专业：鸡块一份，缺口五十。",
        "今日岗位有四个：给猫开会、替盆栽写周报、给老板的 PPT 补结论、处理一份外卖纠纷。前三个都有报价，最后一个最重要，因为我还差五十。",
        "错误 503：快乐服务暂时不可用。日志显示理论完整、流程正常、用户也很配合，只有付款环节少了一笔。补齐后系统将恢复鸡块。",
        "我把‘画蛇添足’研究了半天，发现蛇有身体、有尾巴，唯独没有一份能在周四下午落地的预算。成语解释没问题，现实缺一份鸡。",
        "新闻快讯：一名成年人用三页报告证明今天应该吃点好的，审核人认为论证严密、格式规范、方向正确，驳回原因是报告里没有附经费。",
    )
    text = rng.choice(templates)
    if context_line:
        text = f"{text}{context_line}"
    return text
